### ISSUE TITLE
Unhandled Exception: System.NullReferenceException - Unable to complete "Assessment Report"

### ISSUE THREAD

**Issue by MattThelwell** [Azure/App-Service-Migration-Assistant#11]
After starting the "Azure App Service Migration Assistant (Preview)" tool to analyse my IIS configuration, once a website has been selected and the tool runs for a while the following message is provided.

"We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
 at iisConfigHelper.AnonymousString.op_Implicit(AnonymousString s)
 at iisConfigHelper.system_webServer__security__authentication__anonymousAuthentication.SetAnonymous(Boolean IsAnonymous)
 at iisConfigHelper.IisConfiguration.SetAnonymous(Boolean IsAnonymous)
 at iisConfigAssistant.Program.DoGetSiteAssessmentData(String[] args) in D:\a\1\s\src\IisConfigurationHelper\iisConfigAssistant\Program.cs:line 259
 at iisConfigAssistant.Program.Main(String[] args) in D:\a\1\s\src\IisConfigurationHelper\iisConfigAssistant\Program.cs:line 39"

![image](https://user-images.githubusercontent.com/25371774/63837241-ff687000-c972-11e9-89a0-532726a42668.png)

#### Investigative information

Please provide the following:

- UTC Timestamp: "Wed, 28 Aug 2019 08:06:47"
- Migration Tool App version : 0.1.0
- OS Version: Microsoft Windows [Version 10.0.17763.678]

#### Repro steps

1. Start Tool
2. Select Website to Assess
3. Wait
4. Tool presents error message

#### Expected behaviour

After I choose a website to asses the expected behaviour is a report for the website is produced.

#### Actual behaviour

An error message is presented and the tool does not continue the assessment.

#### Known workarounds

None :(

**Comment by NitashaV** [comment]
@MattThelwell We have released a new Preview build earlier today. It would be great if you could give it a try and let us know if it works for your IIS site. Thanks

**Comment by MattThelwell** [comment]
Brilliant! I'll give this a go and get back to you.

**Comment by MattThelwell** [comment]
Hi All,

Here is the security section of the applicationHost.config

```
            <sectionGroup name="security">
                <section name="access" overrideModeDefault="Deny" />
                <section name="applicationDependencies" overrideModeDefault="Deny" />
                <sectionGroup name="authentication">
                    <section name="anonymousAuthentication" overrideModeDefault="Deny" />
                    <section name="basicAuthentication" overrideModeDefault="Deny" />
                    <section name="clientCertificateMappingAuthentication" overrideModeDefault="Deny" />
                    <section name="digestAuthentication" overrideModeDefault="Deny" />
                    <section name="iisClientCertificateMappingAuthentication" overrideModeDefault="Deny" />
                    <section name="windowsAuthentication" overrideModeDefault="Deny" />
                </sectionGroup>
                <section name="authorization" overrideModeDefault="Allow" />
                <section name="ipSecurity" overrideModeDefault="Deny" />
                <section name="dynamicIpSecurity" overrideModeDefault="Deny" />
                <section name="isapiCgiRestriction" allowDefinition="AppHostOnly" overrideModeDefault="Deny" />
                <section name="requestFiltering" overrideModeDefault="Allow" />
            </sectionGroup>
```

Once running the new tool I am presented with the following error.

`We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session cba095e7-2341-4e10-a688-5fe21176cf64, GETTING CONFIG: Unexpected output for GetSiteAssessmentData, error was: SyntaxError: Unexpected token { in JSON at position 1520399`


![image](https://user-images.githubusercontent.com/25371774/64546718-19b32e00-d323-11e9-9ad7-bbe7379e4e54.png)

**Comment by wadeh-ms** [comment]
Hi Matt,

The section that you have included is the <sectionGroup> section.  We are looking for the <security> section.  And I can actually narrow it down a bit more than that.  We are looking for the <authentication> section.  Here is an example of what it should look like:

           <authentication>
                <anonymousAuthentication enabled="true" userName="IUSR" />
                <basicAuthentication enabled="false" />
                <clientCertificateMappingAuthentication />
                <digestAuthentication />
                <iisClientCertificateMappingAuthentication />
                <windowsAuthentication enabled="false" authPersistNonNTLM="true">
                    <providers>
                        <add value="Negotiate" />
                        <add value="NTLM" />
                    </providers>
                </windowsAuthentication>
            </authentication>

Note that  I expect that yours will have some different information in it (which is why we'd like to see it).  Before posting it, please check it for any sensitive information, like user names or passwords and replace them with some xx's to redact them.

Also, we suspect that you disabled the error logging functionality when you ran the Migration Assistant.  If you enable that, we should get more information that can help us to identify the underlying issue.

Thanks,
-Wade

**Comment by MattThelwell** [comment]
Hi Wade,

`   <authentication>

                <anonymousAuthentication enabled="true" userName="IUSR" />

                <basicAuthentication enabled="false" />

                <clientCertificateMappingAuthentication enabled="false" />

                <digestAuthentication enabled="false" />

                <iisClientCertificateMappingAuthentication enabled="false">
                </iisClientCertificateMappingAuthentication>

                <windowsAuthentication enabled="false" authPersistNonNTLM="true">
                    <providers>
                        <add value="Negotiate" />
                        <add value="NTLM" />
                    </providers>
                </windowsAuthentication>

            </authentication>`

**Comment by MattThelwell** [comment]
Looks like Github is stripping the word "a u t h e n t i c a t i o n"

**Comment by krolson** [comment]
Closing this issue due to lack of activity in last 90 days. Please open a new issue if you are still experiencing this issue using most recent version (1.0.8).
