### ISSUE TITLE
'Newtonsoft.Json.JsonWriter' threw an exception.

### ISSUE THREAD

**Issue by Tank6035** [Azure/App-Service-Migration-Assistant#19]
The Assistant fails when running the basic checks. with the following error:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception. ---> System.IO.FileLoadException
 at Newtonsoft.Json.Utilities.EnumUtils.InitializeValuesAndNames(StructMultiKey`2 key)
 at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
 at Newtonsoft.Json.Utilities.EnumUtils.GetEnumValuesAndNames(Type enumType)
 at Newtonsoft.Json.JsonWriter.BuildStateArray()
 at Newtonsoft.Json.JsonWriter..cctor()
 --- End of inner exception stack trace ---
 at Newtonsoft.Json.JsonWriter..ctor()
 at Newtonsoft.Json.JsonTextWriter..ctor(TextWriter textWriter)
 at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
 at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
 at iisConfigAssistant.Program.Main(String[] args)
![Aasms error](https://user-images.githubusercontent.com/1434171/68706386-5c78c880-0555-11ea-9d2b-294d6df40919.png)
All server are Windows Server 2012 R2
This happens on all servers in this cluster.

**Comment by krolson** [comment]
You refer to the servers as being in a cluster - I am guessing this means they are in a failover cluster? Unfortunately the Migration Assistant does not support clustered IIS servers as a migration source at this time. I have updated the main wiki page with this detail in the FAQs server requirements: https://github.com/Azure/App-Service-Migration-Assistant/wiki.  
Thank you for reporting this. We will consider enabling this type of server source in future and/or improving the error message for this case. If I've misunderstood and your are not using clustered servers please let me know and I will provide instructions for getting some additional debugging information.

**Comment by Tank6035** [comment]
You are correct my server are in a cluster environment.
